### ISSUE TITLE
Linux Support, Docker Containers & Beta Release

### ISSUE THREAD

**Issue by abenck** [WebVella/WebVella-ERP#133]
Hi Everyone,

We want to start trial runs with this to see how we can use this in our current system, but we have a few questions.

1. Will this get linux support soon?
  - I can build this with Microsoft base images ( mcr.microsoft.com/dotnet/core/sdk:3.1 & mcr.microsoft.com/dotnet/core/runtime:3.1 ) with docker, but it's throwing some errors.

2. Is this designed with containerization in mind?
  - We'll run multiple instances of this in the same cluster, will this cause problems?
  - The latest version is throwing this error when trying to run with docker.
  `A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /WebVella.Erp.runtimeconfig.json file specifying the appropriate framework.`

3. Do you have a timeline on when it will leave alpha and be ready for beta/release?

**Comment by bzashev** [comment]
Hey,
thanks for your interest.
It should run on linux as it is asp.net core app and it should not have problems. We haven't tried it personally but we have reports that it runs without problems.
Docker should be ok too, but again I personally didn't tried, just other people sending Ok results.
Cluster should be OK as long as you do not change the schema, entities, pages, meta info like that, as it is cached.
We use it long time now in production, so I can say it is pretty stable. The alpha status is set, because we make changes in the functionalities themselves. We expect this to go to beta once we see how blazor fits in the overall application structure.
Hope that helps
Regards
Boz

**Comment by abenck** [comment]
Hi Boz,

Thanks for the info and quick reply, I'll debug the docker container to see what's happening and report back. We're looking forward to trying this out!

Best Wishes,
Chris

**Comment by abenck** [comment]
Hey Boz,

I have a test container working with the seeded example from the documentation. Are there any missing libraries required in LIBRARIES.md from this repo? I want to build this from source next.

**Comment by bzashev** [comment]
Hey,
excellent news.
No all should be in the nuget dependencies. Have in mind that there are several websites there targeting different plugins (some not finished or not started even).
The project plugin is just some testing and showcase, but an old one.
Most of our work currently is just using the seed and building apps as per customer spec as a plugin. We have about a dozen such production different apps.
If needed you can contact us over discord too.
In brief you should be able to compile all from the source too without a problem

**Comment by abenck** [comment]
Great, Thank you! I joined your discord server.
