### ISSUE TITLE
Ms Sql and MongoDb providers

### ISSUE THREAD

**Issue by weedkiller** [WebVella/WebVella-ERP#134]
Hello, can we make it an option to do Sql Server, Redis for cache or MongoDb.

**Comment by bzashev** [comment]
Hey,
currently there are not plans to support other db then Postgres and frankly we do not see even a reason for that, as it is one of the best right now.
In theory probably it could be made to MS SQL, but MongoDb is surely out of the picture as it requires relational database because of the transactions.

**Comment by weedkiller** [comment]
Thanks for the answer
