### ISSUE TITLE
ErpEvent is not defined

### ISSUE THREAD

**Issue by 28106830** [WebVella/WebVella-ERP#187]
url: https://localhost:54467/sdk/objects/page/l
Version is the latest version

**Comment by 28106830** [comment]
This problem only exists in DEBUG mode

**Comment by bzashev** [comment]
Hey, this probably means that the script.js is not loaded for some reason and this constant is not available because of it. 
The problem that may occur is because of a bug in the .net latest SDK 7.0.201. This make ViewComponents not to be able to be loaded by <vc: taghelper. 
What I would suggest is to temporary until they fix it, to but a global.json in your solution root with the following
{
  "sdk": {
    "version": "7.0.103"
  }
}

And have the 7.0.103 installed (you can check in C:\Program Files\dotnet\sdk
Once you have it, you will need to rebuild the whole solution and then try again.
Hope this helps

**Comment by 28106830** [comment]
thanks
