### ISSUE TITLE
How to join if it is not a private project?

### ISSUE THREAD

**Issue by DaveConsulting** [WebVella/WebVella-ERP#92]
Hi,

I wonder how others could join this project and contribute to it?
I might be missing something, but I couldn't find any requirements, technical design, roadmap or any other kind of information about this project. How could an open source ERP be successful if no one can join the project. I'm sure you know that the community behind an open source is the number one rule to give that project a chance of success.

To prevents confusion, It would be nice to write a few lines on homepage and say that it is actually a private open source project.

**Comment by bzashev** [comment]
Hey Dave,
we haven't got a lot of experience in organizing the open-source part of the software development, so this is more a lack of knowledge or time rather than any intentional act.
Anyone that can help in this will be most welcomed!
The documentation is in our plans for sure, but probably we will start executing on that in the next months. Currently it is more of a simple pull requests and idea discussions.
If you have experience in the management of opensource projects and above all you have the time and the passion, let's discuss. You can contact me whenever you want on our email office@webvella.com
